--- 
title: "Thibaut Plassot"
author: Thibaut Plassot
date: "`r Sys.Date()`"
params:
  pdf_mode: 
    value: FALSE
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
--- 

```{r, include=FALSE}
knitr::opts_chunk$set(
  encoding = 'UTF8',
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions0109.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1Jm2tLHB2pZ-61s0lls5Z4sc5iAooIqnsqIWiq97Iokk/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)


```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
===============================================================================
Información  {#Información }
--------------------------------------------------------------------------------

- <i class="fa fa-calendar-alt"></i> Fecha de Nacimiento: 21/11/1987
- <i class="fa fa-globe"></i> Lugar de Nacimiento: Bordeaux (Francia)
- <i class="fa fa-map-marker-alt"></i> Lugar de Residencia: Ciudad de México (México)



Actualizado el  `r Sys.Date()`.

Contacto {#contact}
--------------------------------------------------------------------------------
- <i class="fa fa-envelope"></i> thiplass@gmail.com
- <i class="fa fa-github"></i> github.com/Thib336
- <i class="fa fa-phone"></i> 7713383120

Programas y lenguaje  {#pr_skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_pr_skill_bars()
```

Idiomas  {#skills}
--------------------------------------------------------------------------------
```{r}
CV %>% print_skill_bars() 
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Realizado con el paquete de R [**pagedown**](https://github.com/rstudio/pagedown). 
Código disponible en [github.com/nstrayer/cv](https://github.com/nstrayer/cv).



Main
================================================================================

Thibaut Plassot {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
 CV %<>% print_text_block("intro")



```

Educación {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
options(encoding = 'UTF-8')
```


Sector Público {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('industy_experience_aside')
```
:::


```{r}
CV %<>% print_section('industry_positions')
```



<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Investigación  {data-icon=laptop}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('research_positions_aside1')
```
:::




```{r}
CV %<>% print_section('research_positions')
```


<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Experiencia como docente  {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```





Documentos de trabajo (Working Papers) {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('about_me_press')
```


<br>
<br>




Publicaciones 
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



Conferencias, Congresos, Seminarios {data-icon=comments}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('conferencias')
```


```{r}
CV %<>% print_links()
```

